<a href="https://colab.research.google.com/github/Fahlevi20/Python/blob/master/Tutorial_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 

In [ ]:
a

array([1, 2, 3])

In [ ]:
b = np.arange(10)

In [ ]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
c = np.arange(10,30,5)

In [ ]:
c

array([10, 15, 20, 25])

In [ ]:
c.shape

(4,)

In [ ]:
d = np.array(([5,6,7],[8,9,10]))

In [ ]:
d

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
d = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [ ]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
d.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
d.shape

(3, 3)

In [17]:
a = np.array([1,2,3])

In [21]:
#@title PERKALIAN DOT

In [ ]:
import numpy as np 

In [ ]:
a = np.array([1,2,3])

In [ ]:
b = np.array([5,6,7])

In [ ]:
c = a*b

In [ ]:
c

array([ 5, 12, 21])